spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.117.130/sell?characterEncoding=utf-8&useSSL=false
  redis:
    host: localhost
    port: 6379
eureka:
  client:
    service-url:
      defaultZone:    http://localhost:8761/eureka/