eureka:
  client:
    service-url: http://localhost:8761/eureka/
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.117.130/sell?characterEncoding=utf-8&useSSL=false
  application:
    name: product
  zipkin:
  # 把链路日志输出到如下指定网址（docker上运行zipkin容器的Ip）
    base-url: http://192.168.99.100:9411/
  sleuth:
    sampler:
    # 设置为1 表示全部输出(可以点进去看,值的单位是百分比)
      percentage: 1
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
logging:
  level:
  # 把下面包下的日志级别调整成debug
    org.springframework.web.client: debug
