eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
#    registerWithEureka: false
#      fetchRegistry: false
#    service-url:
#      defaultZone: http://localhost:8761/eureka/        # \u670D\u52A1\u4E2D\u5FC3\u7AEF\u53E3
#    register-with-eureka: false # \u6539\u6210false\u540E\uFF0C\u4E0D\u4F1A\u628Ahttp://localhost:8761/eureka/\u6CE8\u518C\u5230\u5E94\u7528\u5217\u8868\u91CC
spring:
  application:
    name: eureka
#server:
#  port: 8761    # \u672C\u673A\u7AEF\u53E3 dd